baseURL = "https://nn-study-blog.netlify.app"
languageCode = "en-us"
title = "Nico's Study Notes"
theme = "blowfish"

[outputs]
  home = ["HTML", "RSS"]

[params]
  description = "Writing about what I'm learning"
  showPostSummary = true
  recentPostsCount = 10
